gestionAbsence_index:
    path:     /
    defaults: { _controller: "GestionLpiBundle:Absence:index" }
    methods:  GET

gestionAbsence_show:
    path:     /{id}/show
    defaults: { _controller: "GestionLpiBundle:Absence:show" }
    methods:  GET

gestionAbsence_new:
    path:     /new
    defaults: { _controller: "GestionLpiBundle:Absence:new" }
    options:
            expose: true
    methods:  [GET, POST]


gestionAbsence_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionLpiBundle:Absence:edit" }
    methods:  [GET, POST]

gestionAbsence_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionLpiBundle:Absence:delete" }
    methods:  DELETE
