announce_index:
    path:     /
    defaults: { _controller: "GestionLpiBundle:Announce:index" }
    methods:  GET

announce_show:
    path:     /{id}/show
    defaults: { _controller: "GestionLpiBundle:Announce:show" }
    methods:  GET

announce_new:
    path:     /new
    defaults: { _controller: "GestionLpiBundle:Announce:new" }
    methods:  [GET, POST]

announce_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionLpiBundle:Announce:edit" }
    methods:  [GET, POST]

announce_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionLpiBundle:Announce:delete" }
    methods:  DELETE
