gestionNotes_index:
    path:     /
    defaults: { _controller: "GestionLpiBundle:Notes:index" }
    methods:  GET

gestionNotes_show:
    path:     /{id}/show
    defaults: { _controller: "GestionLpiBundle:Notes:show" }
    methods:  GET

gestionNotes_new:
    path:     /new
    defaults: { _controller: "GestionLpiBundle:Notes:new" }
    options:
            expose: true
    methods:  [GET, POST]

gestionNotes_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionLpiBundle:Notes:edit" }
    methods:  [GET, POST]

gestionNotes_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionLpiBundle:Notes:delete" }
    methods:  DELETE
