<?php

namespace Proxies\__CG__\GestionLpiBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Matiere extends \GestionLpiBundle\Entity\Matiere implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'id', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'nomMatiere', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'description', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'absences', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'notes', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'module', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'compte');
        }

        return array('__isInitialized__', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'id', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'nomMatiere', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'description', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'absences', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'notes', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'module', '' . "\0" . 'GestionLpiBundle\\Entity\\Matiere' . "\0" . 'compte');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Matiere $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomMatiere($nomMatiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomMatiere', array($nomMatiere));

        return parent::setNomMatiere($nomMatiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomMatiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomMatiere', array());

        return parent::getNomMatiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function addAbsence(\GestionLpiBundle\Entity\Absence $absences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAbsence', array($absences));

        return parent::addAbsence($absences);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAbsence(\GestionLpiBundle\Entity\Absence $absences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAbsence', array($absences));

        return parent::removeAbsence($absences);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsences', array());

        return parent::getAbsences();
    }

    /**
     * {@inheritDoc}
     */
    public function addNote(\GestionLpiBundle\Entity\Notes $notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNote', array($notes));

        return parent::addNote($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNote(\GestionLpiBundle\Entity\Notes $notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNote', array($notes));

        return parent::removeNote($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', array());

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setModule(\GestionLpiBundle\Entity\Module $module = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModule', array($module));

        return parent::setModule($module);
    }

    /**
     * {@inheritDoc}
     */
    public function getModule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModule', array());

        return parent::getModule();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompte(\GestionLpiBundle\Entity\Compte $compte = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompte', array($compte));

        return parent::setCompte($compte);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompte', array());

        return parent::getCompte();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
