<?php

namespace GestionLpiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnnounceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnounceRepository extends EntityRepository
{
    public function reverse()
    {
        $query=$this->getEntityManager()->getRepository('GestionLpiBundle:Announce')
            ->createQueryBuilder('a')
            ->select('a')
            ->orderBy('a.id','DESC')->getQuery()->getResult();
        return $query;
    }
}
