<?php

namespace GestionLpiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRepository extends EntityRepository
{
    public function AnnocesByCompte($id){
        $query = $this->getEntityManager()->createQuery(
            'SELECT c,a FROM GestionLpiBundle:Announce a 
                  JOIN a.compte c
                  WHERE c.id = a.compte AND c.id = :id '
        )->setParameter('id',$id);

        if($query->getResult()!=null){
            return $query->getResult();
        }
        return false;
    }
}
