<?php

namespace GestionLpiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends EntityRepository
{
    public function checkAbsance($date = null)
    {
        $date = (isset($date)) ? $date : new \DateTime("now");
        $query = $this->getEntityManager()->getRepository('GestionLpiBundle:Etudiant');
        $result =  $query->createQueryBuilder('e')->select('e.id')
                                       ->join('e.absences','a')
                                       ->andWhere("DATE_FORMAT(a.dateAbsence,'%Y-%m-%d') = DATE_FORMAT(:date,'%Y-%m-%d')")
                                       ->setParameter('date',$date)
                                       ->getQuery()->getResult();
        $arryId =[];
        foreach ($result as $rs){
            $arryId [] = $rs['id'];
        }
        return $arryId;
    }
    public function checkNote ($desc = null)
    {
        $query = $this->getEntityManager()->getRepository('GestionLpiBundle:Etudiant');
        $result = $query->createQueryBuilder('e')->select('e.id')
                                    ->join('e.notes','n')
                                    ->andWhere(n.$desc=e.$desc)
                                    ->setParameter('desc',$desc)
                                    ->getQuery()->getResult();
        $arrayId=[];
        foreach ($result as $rs){
            $arrayId[]=$rs['id'];
        }
        return $arrayId;
    }
}
