<?php

namespace Proxies\__CG__\GestionLpiBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Etudiant extends \GestionLpiBundle\Entity\Etudiant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'id', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'nom', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'prenom', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'cne', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'email', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'dateNaissence', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'dateInscription', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'adresse', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'absences', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'notes');
        }

        return array('__isInitialized__', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'id', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'nom', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'prenom', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'cne', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'email', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'dateNaissence', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'dateInscription', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'adresse', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'absences', '' . "\0" . 'GestionLpiBundle\\Entity\\Etudiant' . "\0" . 'notes');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Etudiant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setCne($cne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCne', array($cne));

        return parent::setCne($cne);
    }

    /**
     * {@inheritDoc}
     */
    public function getCne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCne', array());

        return parent::getCne();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissence($dateNaissence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissence', array($dateNaissence));

        return parent::setDateNaissence($dateNaissence);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissence', array());

        return parent::getDateNaissence();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateInscription($dateInscription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateInscription', array($dateInscription));

        return parent::setDateInscription($dateInscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateInscription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateInscription', array());

        return parent::getDateInscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function addAbsence(\GestionLpiBundle\Entity\Absence $absences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAbsence', array($absences));

        return parent::addAbsence($absences);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAbsence(\GestionLpiBundle\Entity\Absence $absences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAbsence', array($absences));

        return parent::removeAbsence($absences);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsences', array());

        return parent::getAbsences();
    }

    /**
     * {@inheritDoc}
     */
    public function addNote(\GestionLpiBundle\Entity\Notes $notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNote', array($notes));

        return parent::addNote($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNote(\GestionLpiBundle\Entity\Notes $notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNote', array($notes));

        return parent::removeNote($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', array());

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
