<?php

namespace Proxies\__CG__\GestionLpiBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Absence extends \GestionLpiBundle\Entity\Absence implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GestionLpiBundle\\Entity\\Absence' . "\0" . 'id', '' . "\0" . 'GestionLpiBundle\\Entity\\Absence' . "\0" . 'dateAbsence', '' . "\0" . 'GestionLpiBundle\\Entity\\Absence' . "\0" . 'nombreHeurs', '' . "\0" . 'GestionLpiBundle\\Entity\\Absence' . "\0" . 'matiere', '' . "\0" . 'GestionLpiBundle\\Entity\\Absence' . "\0" . 'etudiant');
        }

        return array('__isInitialized__', '' . "\0" . 'GestionLpiBundle\\Entity\\Absence' . "\0" . 'id', '' . "\0" . 'GestionLpiBundle\\Entity\\Absence' . "\0" . 'dateAbsence', '' . "\0" . 'GestionLpiBundle\\Entity\\Absence' . "\0" . 'nombreHeurs', '' . "\0" . 'GestionLpiBundle\\Entity\\Absence' . "\0" . 'matiere', '' . "\0" . 'GestionLpiBundle\\Entity\\Absence' . "\0" . 'etudiant');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Absence $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAbsence($dateAbsence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAbsence', array($dateAbsence));

        return parent::setDateAbsence($dateAbsence);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAbsence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAbsence', array());

        return parent::getDateAbsence();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreHeurs($nombreHeurs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreHeurs', array($nombreHeurs));

        return parent::setNombreHeurs($nombreHeurs);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreHeurs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreHeurs', array());

        return parent::getNombreHeurs();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatiere(\GestionLpiBundle\Entity\Matiere $matiere = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatiere', array($matiere));

        return parent::setMatiere($matiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatiere', array());

        return parent::getMatiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtudiant(\GestionLpiBundle\Entity\Etudiant $etudiant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtudiant', array($etudiant));

        return parent::setEtudiant($etudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtudiant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtudiant', array());

        return parent::getEtudiant();
    }

}
